POST http://localhost:8080
content-type: application/json

{
    "code": "#include<stdio.h>\nmain()\n{\n  printf(\"Hello World\");\n}",
    "lang": "c"
}

###
POST http://localhost:8080
content-type: application/json

{
    "code": "#include<stdio.h>\nmain)\n{\n  printf(\"Hello World\");\n}",
    "lang": "c"
}

###
POST http://localhost:8080
content-type: application/json

{
    "code": "#include<stdio.h>\nmain()\n{\n  printf(\"%d\",5);\n}",
    "lang": "cpp"
}